<?php
///////////////////////////////
echo' <div class="okno">';
echo'	<a href="../index.php">';
echo'		<div class=text>';
echo'			<span class="ikona glyphicon glyphicon-chevron-down" aria-hidden="true"></span>';
echo'			Strona główna';
echo'		</div>';
echo'	</a>';
echo' </div>';
/////////////////////////////

echo' <div class="container">';
echo'    <div class="row">';
echo'        <div class="col-sm-3 col-md-3">';
echo'            <div class="panel-group" id="accordion">';
echo'                <div class="panel panel-default">';
echo'                    <div class="panel-heading">';
echo'                        <h4 class="panel-title">';
echo'                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">';
echo'                            </span>Artykuły</a>';
echo'                        </h4>';
echo'                    </div>';
echo'                    <div id="collapseOne" class="panel-collapse collapse in">';
echo'                        <div class="panel-body">';
echo'                            <table class="table">';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-pencil text-primary"></span><a href="licencjat-dobry/admin/article/articleCreate.php">Stwórz</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-flash text-success"></span><a href="article/articleManageKat.php">Przeglądaj</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>';
echo'                                        <span class="badge">42</span>';
echo'                                    </td>';
echo'                                </tr>';
echo'                           </table>';
echo'                        </div>';
echo'                    </div>';
echo'                </div>';
echo'                <div class="panel panel-default">';
echo'                    <div class="panel-heading">';
echo'                        <h4 class="panel-title">';
echo'                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">';
echo'                            </span>Samouczki</a>';
echo'                        </h4>';
echo'                    </div>';
echo'                    <div id="collapseTwo" class="panel-collapse collapse">';
echo'                        <div class="panel-body">';
echo'                            <table class="table">';
echo'                               <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Invoices</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Shipments</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                   <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Tex</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                            </table>';
echo'                        </div>';
echo'                    </div>';
echo'                </div>';
echo'                <div class="panel panel-default">';
echo'                    <div class="panel-heading">';
echo'                       <h4 class="panel-title">';
echo'                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">';
echo'                            </span>Quizy</a>';
echo'                        </h4>';
echo'                    </div>';
echo'                    <div id="collapseThree" class="panel-collapse collapse">';
echo'                        <div class="panel-body">';
echo'                            <table class="table">';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Change Password</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>';
echo'                                    </td>';
echo'                               </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <a href="http://www.jquery2dotnet.com">Import/Export</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                   <td>';
echo'                                        <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">';
echo'                                            Delete Account</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                            </table>';
echo'                        </div>';
echo'                    </div>';
echo'                </div>';
echo'                <div class="panel panel-default">';
echo'                    <div class="panel-heading">';
echo'                        <h4 class="panel-title">';
echo'                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">';
echo'                            </span>Reports</a>';
echo'                        </h4>';
echo'                    </div>';
echo'                    <div id="collapseFour" class="panel-collapse collapse">';
echo'                        <div class="panel-body">';
echo'                            <table class="table">';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                                <tr>';
echo'                                    <td>';
echo'                                        <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>';
echo'                                    </td>';
echo'                                </tr>';
echo'                            </table>';
echo'                        </div>';
echo'                    </div>';
echo'                </div>';
echo'            </div>';
echo'        </div>';
        

?>